# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Client.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 775)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_Log = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_Log.setGeometry(QtCore.QRect(20, 370, 761, 351))
        self.textBrowser_Log.setObjectName("textBrowser_Log")
        self.checkBox_CANFD = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_CANFD.setGeometry(QtCore.QRect(580, 50, 81, 20))
        self.checkBox_CANFD.setObjectName("checkBox_CANFD")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 350, 781, 381))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_TesterPresent = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_TesterPresent.setGeometry(QtCore.QRect(200, 110, 111, 20))
        self.radioButton_TesterPresent.setObjectName("radioButton_TesterPresent")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 310, 91, 21))
        self.label.setObjectName("label")
        self.lineEdit_InputData = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_InputData.setGeometry(QtCore.QRect(100, 310, 131, 31))
        self.lineEdit_InputData.setObjectName("lineEdit_InputData")
        self.pushButton_Send = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Send.setGeometry(QtCore.QRect(240, 310, 93, 35))
        self.pushButton_Send.setObjectName("pushButton_Send")
        self.checkBox_CAN = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_CAN.setGeometry(QtCore.QRect(680, 50, 61, 20))
        self.checkBox_CAN.setObjectName("checkBox_CAN")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 120, 211, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_PhysicalAddr = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_PhysicalAddr.setGeometry(QtCore.QRect(20, 30, 131, 20))
        self.checkBox_PhysicalAddr.setObjectName("checkBox_PhysicalAddr")
        self.checkBox_FunctionAddr = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_FunctionAddr.setGeometry(QtCore.QRect(120, 30, 81, 20))
        self.checkBox_FunctionAddr.setObjectName("checkBox_FunctionAddr")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(560, 20, 211, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_ReadDTCs = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ReadDTCs.setGeometry(QtCore.QRect(430, 240, 93, 35))
        self.pushButton_ReadDTCs.setObjectName("pushButton_ReadDTCs")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(420, 220, 251, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_ClearDTCs = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_ClearDTCs.setGeometry(QtCore.QRect(140, 20, 93, 35))
        self.pushButton_ClearDTCs.setObjectName("pushButton_ClearDTCs")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_7.setGeometry(QtCore.QRect(-430, 10, 251, 71))
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_11.setGeometry(QtCore.QRect(140, 20, 93, 35))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_DefaultSession = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DefaultSession.setGeometry(QtCore.QRect(40, 39, 141, 35))
        self.pushButton_DefaultSession.setObjectName("pushButton_DefaultSession")
        self.pushButton_ProgramSession = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ProgramSession.setGeometry(QtCore.QRect(40, 80, 141, 35))
        self.pushButton_ProgramSession.setObjectName("pushButton_ProgramSession")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(19, 11, 311, 201))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_ExtendedSession = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_ExtendedSession.setGeometry(QtCore.QRect(20, 110, 141, 35))
        self.pushButton_ExtendedSession.setObjectName("pushButton_ExtendedSession")
        self.pushButton_BoschSession = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_BoschSession.setGeometry(QtCore.QRect(20, 150, 141, 35))
        self.pushButton_BoschSession.setObjectName("pushButton_BoschSession")
        self.pushButton_UnlockLevel1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_UnlockLevel1.setGeometry(QtCore.QRect(370, 46, 125, 35))
        self.pushButton_UnlockLevel1.setObjectName("pushButton_UnlockLevel1")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(350, 10, 161, 201))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_BoschUnlock = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_BoschUnlock.setGeometry(QtCore.QRect(20, 140, 121, 35))
        self.pushButton_BoschUnlock.setObjectName("pushButton_BoschUnlock")
        self.pushButton_UnlockLevel2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_UnlockLevel2.setGeometry(QtCore.QRect(370, 100, 121, 35))
        self.pushButton_UnlockLevel2.setObjectName("pushButton_UnlockLevel2")
        self.pushButton_Connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Connect.setGeometry(QtCore.QRect(60, 240, 93, 35))
        self.pushButton_Connect.setObjectName("pushButton_Connect")
        self.pushButton_Disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Disconnect.setGeometry(QtCore.QRect(200, 240, 93, 35))
        self.pushButton_Disconnect.setObjectName("pushButton_Disconnect")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 220, 311, 71))
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButton_ClearLog = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ClearLog.setGeometry(QtCore.QRect(660, 380, 93, 35))
        self.pushButton_ClearLog.setObjectName("pushButton_ClearLog")
        self.pushButton_SaveLog = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SaveLog.setGeometry(QtCore.QRect(660, 420, 93, 35))
        self.pushButton_SaveLog.setObjectName("pushButton_SaveLog")
        self.groupBox_8.raise_()
        self.groupBox_6.raise_()
        self.groupBox_5.raise_()
        self.groupBox_4.raise_()
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.textBrowser_Log.raise_()
        self.checkBox_CANFD.raise_()
        self.radioButton_TesterPresent.raise_()
        self.label.raise_()
        self.lineEdit_InputData.raise_()
        self.pushButton_Send.raise_()
        self.checkBox_CAN.raise_()
        self.groupBox_2.raise_()
        self.pushButton_ReadDTCs.raise_()
        self.pushButton_DefaultSession.raise_()
        self.pushButton_ProgramSession.raise_()
        self.pushButton_UnlockLevel1.raise_()
        self.pushButton_UnlockLevel2.raise_()
        self.pushButton_Connect.raise_()
        self.pushButton_Disconnect.raise_()
        self.pushButton_ClearLog.raise_()
        self.pushButton_SaveLog.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 26))
        self.menubar.setObjectName("menubar")
        self.menuConfig = QtWidgets.QMenu(self.menubar)
        self.menuConfig.setObjectName("menuConfig")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionConfig = QtWidgets.QAction(MainWindow)
        self.actionConfig.setObjectName("actionConfig")
        self.actionDiagnostic = QtWidgets.QAction(MainWindow)
        self.actionDiagnostic.setObjectName("actionDiagnostic")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuConfig.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuConfig.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Remote Diag - V2"))
        self.checkBox_CANFD.setText(_translate("MainWindow", "CANFD"))
        self.groupBox.setTitle(_translate("MainWindow", "Log"))
        self.radioButton_TesterPresent.setText(_translate("MainWindow", "Tester Present"))
        self.label.setText(_translate("MainWindow", "Tx Diagnostic"))
        self.pushButton_Send.setText(_translate("MainWindow", "Send"))
        self.checkBox_CAN.setText(_translate("MainWindow", "CAN"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Addressing Method"))
        self.checkBox_PhysicalAddr.setText(_translate("MainWindow", "Physical"))
        self.checkBox_FunctionAddr.setText(_translate("MainWindow", "Function"))
        self.groupBox_3.setTitle(_translate("MainWindow", "CAN Type"))
        self.pushButton_ReadDTCs.setText(_translate("MainWindow", "Read DTCs"))
        self.groupBox_4.setTitle(_translate("MainWindow", "DTCs"))
        self.pushButton_ClearDTCs.setText(_translate("MainWindow", "Clear DTCs"))
        self.groupBox_7.setTitle(_translate("MainWindow", "DTCs"))
        self.pushButton_11.setText(_translate("MainWindow", "Clear DTCs"))
        self.pushButton_DefaultSession.setText(_translate("MainWindow", "Default Session"))
        self.pushButton_ProgramSession.setText(_translate("MainWindow", "Programming Session"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Diag Control"))
        self.pushButton_ExtendedSession.setText(_translate("MainWindow", "Extended Session"))
        self.pushButton_BoschSession.setText(_translate("MainWindow", "Bosch Session"))
        self.pushButton_UnlockLevel1.setText(_translate("MainWindow", "Security Application"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Security Access"))
        self.pushButton_BoschUnlock.setText(_translate("MainWindow", "Security Bosch"))
        self.pushButton_UnlockLevel2.setText(_translate("MainWindow", "Security FBL"))
        self.pushButton_Connect.setText(_translate("MainWindow", "Connect"))
        self.pushButton_Disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.groupBox_8.setTitle(_translate("MainWindow", "IsConnectServer"))
        self.pushButton_ClearLog.setText(_translate("MainWindow", "Clear log"))
        self.pushButton_SaveLog.setText(_translate("MainWindow", "Save log"))
        self.menuConfig.setTitle(_translate("MainWindow", "Config"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionConfig.setText(_translate("MainWindow", "Server"))
        self.actionDiagnostic.setText(_translate("MainWindow", "Project Diagnostic"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))

