# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(504, 395)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(90, 213, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 155, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(90, 184, 64, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_ResponseID = QtWidgets.QLineEdit(Form)
        self.lineEdit_ResponseID.setGeometry(QtCore.QRect(190, 211, 81, 22))
        self.lineEdit_ResponseID.setObjectName("lineEdit_ResponseID")
        self.lineEdit_FunctionID = QtWidgets.QLineEdit(Form)
        self.lineEdit_FunctionID.setGeometry(QtCore.QRect(190, 182, 81, 22))
        self.lineEdit_FunctionID.setObjectName("lineEdit_FunctionID")
        self.pushButton_Load_ConfigFie = QtWidgets.QPushButton(Form)
        self.pushButton_Load_ConfigFie.setGeometry(QtCore.QRect(80, 340, 93, 28))
        self.pushButton_Load_ConfigFie.setObjectName("pushButton_Load_ConfigFie")
        self.pushButton_Save_ConfigFile = QtWidgets.QPushButton(Form)
        self.pushButton_Save_ConfigFile.setGeometry(QtCore.QRect(330, 340, 93, 28))
        self.pushButton_Save_ConfigFile.setObjectName("pushButton_Save_ConfigFile")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(90, 243, 64, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_Display_SecurityDll_Path = QtWidgets.QLineEdit(Form)
        self.lineEdit_Display_SecurityDll_Path.setGeometry(QtCore.QRect(190, 240, 231, 22))
        self.lineEdit_Display_SecurityDll_Path.setObjectName("lineEdit_Display_SecurityDll_Path")
        self.lineEdit_PhysicalID = QtWidgets.QLineEdit(Form)
        self.lineEdit_PhysicalID.setGeometry(QtCore.QRect(190, 153, 81, 22))
        self.lineEdit_PhysicalID.setObjectName("lineEdit_PhysicalID")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 123, 381, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.toolButton_Load_Security_Dll = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_Load_Security_Dll.setGeometry(QtCore.QRect(100, 120, 27, 22))
        self.toolButton_Load_Security_Dll.setObjectName("toolButton_Load_Security_Dll")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(30, 150, 64, 16))
        self.label_7.setObjectName("label_7")
        self.toolButton_Load_DTCExcel = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_Load_DTCExcel.setGeometry(QtCore.QRect(100, 150, 27, 22))
        self.toolButton_Load_DTCExcel.setObjectName("toolButton_Load_DTCExcel")
        self.lineEdit_Dispaly_DTCExcel_Path = QtWidgets.QLineEdit(Form)
        self.lineEdit_Dispaly_DTCExcel_Path.setGeometry(QtCore.QRect(190, 270, 231, 22))
        self.lineEdit_Dispaly_DTCExcel_Path.setObjectName("lineEdit_Dispaly_DTCExcel_Path")
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setGeometry(QtCore.QRect(60, 20, 381, 91))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setGeometry(QtCore.QRect(30, 60, 23, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_IP = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_IP.setGeometry(QtCore.QRect(70, 30, 111, 22))
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setGeometry(QtCore.QRect(30, 31, 53, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_Port = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_Port.setGeometry(QtCore.QRect(70, 59, 51, 22))
        self.lineEdit_Port.setObjectName("lineEdit_Port")
        self.groupBox_2.raise_()
        self.label_5.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.lineEdit_ResponseID.raise_()
        self.lineEdit_FunctionID.raise_()
        self.pushButton_Load_ConfigFie.raise_()
        self.pushButton_Save_ConfigFile.raise_()
        self.label_6.raise_()
        self.lineEdit_Display_SecurityDll_Path.raise_()
        self.lineEdit_PhysicalID.raise_()
        self.lineEdit_Dispaly_DTCExcel_Path.raise_()
        self.groupBox_7.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Response ID"))
        self.label_3.setText(_translate("Form", "Physical ID"))
        self.label_4.setText(_translate("Form", "Function ID"))
        self.pushButton_Load_ConfigFie.setText(_translate("Form", "Load"))
        self.pushButton_Save_ConfigFile.setText(_translate("Form", "Save"))
        self.label_6.setText(_translate("Form", "Security Dll"))
        self.groupBox_2.setTitle(_translate("Form", "Diagnostic config"))
        self.toolButton_Load_Security_Dll.setText(_translate("Form", "..."))
        self.label_7.setText(_translate("Form", "DTC excel"))
        self.toolButton_Load_DTCExcel.setText(_translate("Form", "..."))
        self.groupBox_7.setTitle(_translate("Form", "Server config"))
        self.label_8.setText(_translate("Form", "Port"))
        self.label_2.setText(_translate("Form", "IP"))

